Description: API Resources

Transform: AWS::LanguageExtensions

Parameters:
  Environment:
    Type: String

Resources:
  ApiRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: !Sub apigateway.${AWS::URLSuffix}
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: '*'
          PolicyName: !Sub ${Environment}-ApiLambdaInvokePermission

  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub ${Environment} {{ cookiecutter.project }} API
      Description: {{ cookiecutter.project }} API

Outputs:
  RestApiId:
    Value: !Ref RestApi
  RootResourceId:
    Value: !GetAtt RestApi.RootResourceId
  ApiRoleArn:
    Value: !GetAtt ApiRole.Arn
